[api]
url="https://infisical.example.com"
client_id="01234567-89ab-cdef-0123-4567890abcde"
client_secret="0123456789012345678901234567890123456789012345678901234567890123"
token="abcdefghijklmnopqrstuvwxyzABCDEFGHIJ.LMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMN.PQRSTUVWXYZ-123456789ab_defghijklmnopqrstuv"
org_id="01234567-89ab-cdef-0123-4567890abcde"
